

In the infant paradigm, infants are familiarized to six unique stimuli for different exposure durations within a single session in a blocked design. This is in contrast to the standard infant familiarization/habituation paradigm in which infants are familiarized to only one stimulus throughout the experiment, which makes the effect of exposure duration difficult to estimate. By presenting infants with multiple blocks with varying familiarization times, we can directly measure the effect of familiarization on looking time within participants.

To get a dense estimate of exposure durations, we pre-registered and ran two experiments, sequentially, with two sets of exposure durations. The first experiment showed infants blocks of 0, 4 or 8 familiarizations (Exp A; pre-registered [here](https://osf.io/gux4f/?view_only=b4d6d0118dfa41a79fb431d389f4fecc)). The second experiment showed infants blocks of 1, 3 or 9 familiarizations (Exp B; pre-registered [here](https://osf.io/w6pgu/?view_only=39ee108159884761a0c5bc68d11918df)).

## Participants

```{r}
n_subject_expA <- nrow(infant_d %>% filter(experiment == 'A') %>% distinct(subject_num))
n_subject_expB <- nrow(infant_d %>% filter(experiment == 'B') %>% distinct(subject_num))
n_subject_total <- n_subject_expA + n_subject_expB

mean_age <- infant_d %>% group_by(experiment, subject_num) %>% summarize(age_in_months = mean(age)/30) %>% pull(age_in_months) %>% mean() %>% round(2)

# demographics
age_sex_df = infant_d %>% distinct(experiment, subject_num, age, sex) %>% mutate(age_in_months = age/30) 
mean_age = age_sex_df %>% pull(age_in_months) %>% mean() %>% round(2)
sex =  age_sex_df %>% count(sex)

# exclusions

complete_exclusions <- infant_d %>% distinct(experiment, subject_num, exclude) %>% 
  group_by(subject_num, experiment) %>% filter(n() == 1, exclude) 

n_complete_exclusions = complete_exclusions %>% nrow()

n_complete_exclusions_expA = complete_exclusions %>% filter(experiment == 'A') %>% nrow()

n_complete_exclusions_expB = complete_exclusions %>% filter(experiment == 'B') %>% nrow()

# copy
excluded_df = infant_d

for (x in 1:n_complete_exclusions) {
  excluded_subj = complete_exclusions[x,]
  excluded_df %<>% filter(!(subject_num == excluded_subj$subject_num & experiment == excluded_subj$experiment))
}

num_excluded_trials = excluded_df %>% filter(fam_or_test == 'test') %>% count(exclude) %>% filter(exclude) %>% pull(n)

```

We tested a combined sample of `r n_subject_total` 7-10 month old infants, with `r n_subject_expA` in Exp A and `r n_subject_expB` in Exp B ($M_{age}$ = `r mean_age` months, `r sex$n[sex$sex == 'F']` female). `r n_complete_exclusions` participants were excluded completely due to fussiness. We also excluded an additional `r num_excluded_trials` individual test trials in which 1) infants looked at the stimuli for less than a total 2 seconds, 2) there were momentary external distractions in the home of the infant or 3) the gaze classifier (see **Looking time coding**) had an average classification confidence of less than 50%. Data collection was performed synchronously on Zoom, and infants were recruited from Lookit [@scott2017lookit] and Facebook. 


## Stimuli

Infants saw a different stimulus set from the preschoolers. In two initial studies, not shown here, we showed infants the Spore stimulus set used in preschoolers, in a slightly different experimental paradigm, and failed to elicit replicable habituation, novelty or familiarity preferences. In the current studies, we presented infants with a series of animated animals, which we created using "Quirky Animals" assets from Unity [link](https://tinyurl.com/469xxrn7). The animals were walking, crawling or swimming, depending on the species.

## Procedure

This experiment followed a block structure, where each block was divided into two sections: 1) a familiarization period and 2) a test event. Each block was preceded by our lab-standard attention getter, a salient rotating star. During the familiarization period, the infant was familiarized to a particular animal, the background, in a series of familiarization trials. Each familiarization trial was a 5 second sequence: curtains open for 1 second, the animated animal was presented for 3 seconds, and then the curtains closed again for 1 second. We refer to the number of times the curtain opened and closed as the "familiarization duration", which varied between blocks.

During the test event, the infant saw either the same background animal again, or a novel animal, the deviant. The onset of the test event was not marked by any visual markers, but a bell sound is played as the curtains open, to maximize the chance of engagement during the test trial. The test event used an infant-controlled procedure, in which the experimenter terminated the trial when the infant looked away for more than three consecutive seconds. Looking time was defined as the total time that the infant spends looking at the screen from the onset of the stimulus until the first two consecutive seconds of the infant looking away from the screen. The discrepancy between the experimenter criterion and the looking time criterion was to be conservative in stopping trials to avoid early trial terminations. If the infant did not look away after 60 seconds of being presented with the test event, the next block automatically began and infants’ looking time for this test event was recorded as 60 seconds.

Each baby saw six blocks: Three different familiarization durations (0, 4 and 8 in Exp. A, and 1, 3 and 9 in Exp. B) appeared twice each, once for each test event type (background or deviant). 

## Looking time coding
To code the infants’ gaze we used iCatcher+, a validated tool developed for robust and automatic annotation of infants’ gaze direction from video [@erel2022icatcher]. To obtain trial-wise looking times, we merged iCatcher+ annotations with trial timing information, thereby fully replacing manual coding of looking times. 