

# cache pre-registered models
```{r eval=FALSE, include=FALSE}

# prepare fam and test df with exclusions
fam_df = infant_d %>% filter(fam_or_test == 'fam', !exclude) %>% mutate(fam_duration = as.numeric(fam_duration))
test_df = infant_d %>% filter(fam_or_test == 'test', !exclude) %>% mutate(fam_duration = as.numeric(fam_duration))


# EXP3 only

# checking for non-linearity model
model_1a <- lmer(log(LT) ~ poly(fam_duration,2) *test_type + trial_num + (1 | subject_num), data = test_df)


# reparameterized to check for slope on 
model_1b <- lmer(log(LT) ~ poly(fam_duration,2) *test_type + trial_num + (1 | subject_num), data = test_df %>% mutate(test_type = factor(test_type, levels = c("nov", "fam"))))


# fam pref (EXPLORATORY)
model_2a <- lmer(log(LT) ~ test_type + trial_num + (1 | subject_num), data = test_df %>% filter(experiment == 'A', fam_duration == 4))

# fam pref pre-registered?
model_2b <- lmer(log(LT) ~ test_type + trial_num + (1 | subject_num), data = test_df %>% filter(fam_duration <= 4 & fam_duration != 0))

# dishabituation
model_3a <- lmer(log(LT) ~ test_type + trial_num + (1 | subject_num), data = test_df %>% filter(fam_duration == 8))

model_3b <- lmer(log(LT) ~ test_type + trial_num + (1 | subject_num), data = test_df %>% filter(fam_duration == 9))

model_3c <- lmer(log(LT) ~ test_type + trial_num + (1 | subject_num), data = test_df %>% filter(fam_duration >= 8))


saveRDS(model_1a, here("cached_data/infants/model_1a.rds"))
saveRDS(model_1b, here("cached_data/infants/model_1b.rds"))
saveRDS(model_2a, here("cached_data/infants/model_2a.rds"))
saveRDS(model_2b, here("cached_data/infants/model_2b.rds"))
saveRDS(model_3a, here("cached_data/infants/model_3a.rds"))
saveRDS(model_3b, here("cached_data/infants/model_3b.rds"))
saveRDS(model_3c, here("cached_data/infants/model_3c.rds"))

```


To test the prediction that partial encoding elicits familiarity preferences,
while complete encoding elicits novelty preferences, we pre-registered a model
which allows for a non-linear interaction between exposure duration by adding a 
quadratic effect of familiarization duration, and its interaction with novelty. 
We found that neither the main effect, nor the interaction of that quadratic term were significant (Model 1a; main effect & interaction of poly2 terms), while the interaction of novelty with the linear term was significant (Model 1a; interaction of poly1 terms). This suggests that novelty preferences get stronger as a function familiarization duration, but that there is no special effect of partial encoding as posited by H&A. Furthermore, there was a significant decrease in looking times to the familiar items as a function of familiarization duration (Model 1a, poly(fam_duration, 1)), indicating that infants habituated to familiar stimuli in our paradigm.
We next tested specifically for the existence of familiarity preference in our dataset. After finding a hint of a familiarity preference after four familiarizations in the first study, which did not turn out significant in an exploratory analysis (Model 2a: test type effect), we argued that if familiarity preferences are driven by partial encoding, any condition in which there were fewer exposures should also reveal a familiarity preference. We therefore tested whether looking to the familiar stimulus was longer in all trial with four or less exposures, which it did not (Model 2b; test type effect). Novelty preferences on the other hand were robust after 8 (Model 3a; test type effect) and 9 familiarizations (Model 3b; test type effect), as well as in the combined dataset (Model 3c; test type effect).



