Overall, we developed a new looking time paradigm for infants and preschoolers which tests the relationship between exposure duration and the duration of attention, within-subjects. Using this paradigm, we found evidence for habituation and novelty preferences across all ages tested. In contrast, despite prematurely interrupting familiarization to induce partial encoding, we failed to find attentional preferences for familiar stimuli in either preschoolers or infants. Limited exposure did not lead to familiarity preferences. 

Both the presence of habituation and novelty preferences and the absence of familiarity preferences were consistent across age groups (and similar to previous results in adults), suggesting developmental continuity of the dynamics of attention in this paradigm. For simple visual events presented sequentially, the decision of how long to look at a stimulus, and when to look away, can therefore be explained by a simple information gain model, like the one presented in @cao2022habituation, across the lifespan. 

Our failure to find familiarity preferences, in a within-subjects design targeting partial encoding, should generate caution when inferring familiarity preferences, post-hoc, in similar experiments. Note, though, that the absence of familiarity preferences in our results does not rule out their existence, in our paradigm or in general. 

First, familiarity preferences may be more subtle than novelty preferences, so that the statistical power that is needed to find familiarity preferences is higher than that achieved in the current study. A current large-scale study by the ManyBabies consortium which aims to test the predictions made by H&A may give insight into this possibility [@kosie2023manybabies].  

Second, evoking familiarity preferences may depend on the presentation mode of stimuli: In our studies participants saw one stimulus, familiar or novel, at a time. By contrast, many studies reporting familiarity preferences follow a preferential looking set-up in which infants are presented with both familiar and novel stimuli simultaneously, and their relative looking time to each is recorded [@roder2000infants; @thiessen2003cues; @rose1982familiarity]. Familiarity preferences could arise due to the *recognition* of a familiar stimulus among other stimuli, in which case the current paradigm would not be suited to detect them [though see @gustafsson2021visual].

Third, affective processes might drive familiarity preferences. The “mere exposure effect” is widely documented in social psychology: brief exposure to a particular stimulus can be sufficient to induce positive affect associated with that stimulus [@zajonc1968attitudinal; @montoya2017re]. Therefore, it is possible that familiarity preferences arise in infants when the familiar stimulus evokes positive affect. Including measurements that more directly tap into liking, such as reaching or pointing [@woo2022human; @powell2022adopted], and relating them to looking time, may help isolate the contribution of affect in familiarity preferences.

Finally, and most importantly, the learning problem that people are solving likely plays a critical role in whether they will exhibit familiarity preferences. This context-dependence is reflected in meta-analyses investigating familiarity preferences in different paradigms. For example, when tested on word segmentation in their native language, infants show a persistent preference for familiar stimuli throughout the first year [@bergmann2016development]. In contrast, when tested on statistical learning of novel words, infants show a consistent preference for novel stimuli, from 4-month- to 11 months of age [@black2017quantifying]. These seemingly contradictory results highlight the need for theories that formalize accounts of how the learning problem influences optimal attention. @dubey2020reconciling give an example of such a formal account by showing that when past and present events are correlated, a tendency to attend to familiar events may arise to prepare for the most likely future events, while in uncorrelated environments, novelty preferences are optimal (under some assumptions). Similarly, in a rational analysis of attentional preferences, @cao2022habituation show that ideal learners attempting to maximize their expected information gain consistently seek novelty when trying to learn a single concept. But it is possible that once the learning goal or constraints on learning change e.g. by attempting to learn hierarchical concepts or imposing switch costs on learning new concepts, optimal information-seeking may include a phase of attending to familiar stimuli.

## Conclusion 

In conclusion, we find robust evidence for habituation and novelty preferences in preschoolers and infants. In the same paradigms, we find no evidence for familiarity preferences, despite attempting to impose partial encoding through a new experimental paradigm in which we manipulate exposure duration within-subjects. Our findings suggest that familiarity preferences do not necessarily arise after limited exposure to stimuli, so post-hoc inferences of familiarity preferences in infant looking time data should be made with care. Instead, we conclude that developmental psychology needs formal models to make specific predictions for the conditions under which infants will, and will not, show familiarity preferences, that can then be rigorously tested in experiments.